import pandas as pd
temp=pd.read_excel("C:/Users/admin/Desktop/city temperature assignment 1.xlsx")
temp.head()
temp.tail()
temp.info()
temp.surat.mean()
temp.surat.median()
temp.surat.mode()
temp.surat.std()
temp.surat.var()
temp.surat.skew()
temp.surat.kurt()
temp.surat.hist()
temp.surat.mode()
temp.surat.value_counts() 
temp.hydrabed.mean()
temp.hydrabed.median()
temp.hydrabed.mode()
temp.hydrabed.std()
temp.hydrabed.var()
temp.hydrabed.skew()
temp.hydrabed.kurt()
temp.hydrabed.hist()
temp.hydrabed.mode()
temp.hydrabed.value_counts() 